account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name="register"),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_managment/forgot.html',
            email_template_name='password_managment/password_reset_email.html',
            success_url=reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_managment/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_managment/reset.html',
             success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_managment/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.log_out, name="log_out")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
import store.urls
import account.urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(store.urls)),
    path('user/', include(account.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name="index"),
    path('store/', views.store, name="store"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('product/<int:pk>/', views.product, name="product"),
    path('update_item/', views.update_item, name="update_item"),
    path('payment/', views.payment, name="payment"),
    path('payment_output/', views.payment_output, name="payment_output")
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.

class MyAccountManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        
        return user
    
    def create_superuser(self, email, password):
        user = self.create_user(email=self.normalize_email(email), password=password)
        
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        
        user.save(using=self._db)
        return user
    
class Account(AbstractBaseUser):
    email = models.EmailField(max_length=100, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    USERNAME_FIELD = 'email'
    
    objects = MyAccountManager()
    
    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
    
    

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import Account
from store.models import CustomerModel

class CreateAccountForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Add a valid email addres")
    
    class Meta:
        model = Account
        fields = ('email', 'password1', 'password2')
       
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)   
        except:
            return email
        raise forms.ValidationError(f'Email {email} is already in use')
        
class CreateCustomerForm(forms.ModelForm):
    
    class Meta:
        model = CustomerModel
        fields = ('first_name', 'last_name')
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name.lower()
        else:
            raise forms.ValidationError('First Name must be alphabetical')
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name.lower()
        else:
            raise forms.ValidationError('Last Name must be alphabetical')  
      
      
      
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=200)
    password = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput()
    )
        
        
class UserShippingDataForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=200)
    address = forms.CharField(max_length=200)
    city = forms.CharField(max_length=200)
    state = forms.CharField(max_length=200)
    zipcode = forms.CharField(max_length=200)    
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)   
        except:
            return email
        raise forms.ValidationError(f'Email {email} is already in use')
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name.lower()
        else:
            raise forms.ValidationError('First Name must be alphabetical')
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name.lower()
        else:
            raise forms.ValidationError('Last Name must be alphabetical')  

class UserDataForm(forms.Form):
    first_name = forms.CharField(max_length=50, label='First Name')
    last_name = forms.CharField(max_length=50, label='Last Name')
    email = forms.EmailField(max_length=200, label='Email')
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label='Repeat password',
        strip=False,
        widget=forms.PasswordInput()
    )
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError('Confirm your password')
        if password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2
        
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)   
        except:
            return email
        raise forms.ValidationError(f'is already in use')
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name.lower()
        else:
            raise forms.ValidationError('First Name must be alphabetical')
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name.lower()
        else:
            raise forms.ValidationError('Last Name must be alphabetical')  

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from .forms import *
from .models import Account
from django.contrib.auth import logout
from django.contrib.auth.hashers import make_password
from store.models import CustomerModel


# Create your views here.
def user_login(request):
    if request.user.is_authenticated:
        return redirect('/')

    context = {}
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(
                email=email,
                password=password,
                backend='account.backends.CaseInsensitiveModelBackend')
            if user is not None:
                login(request,
                      user,
                      backend='account.backends.CaseInsensitiveModelBackend')
                response = redirect('/')
                response.delete_cookie('cart')
                return response
        else:
            context['loginform'] = form
    return render(request, 'user/login.html', context)


def register(request):

    if request.user.is_authenticated:
        return redirect('/')
    context = {}

    if request.POST:
        userform = UserDataForm(request.POST)
        if userform.is_valid():

            #Creating an account based in the form data
            email = userform.cleaned_data.get('email')
            raw_password = userform.cleaned_data.get('password2')
            first_name = userform.cleaned_data.get('first_name')
            last_name = userform.cleaned_data.get('last_name')
            account = Account.objects.create_user(email=email,
                                                  password=raw_password)

            #Linking the created account with a customermodel
            customer, created = CustomerModel.objects.get_or_create(
                email=email)
            customer.user = account
            customer.first_name = first_name
            customer.last_name = last_name
            customer.save()

            if account is not None:
                login(request,
                      account,
                      backend='account.backends.CaseInsensitiveModelBackend')
            return redirect('/')
        else:
            context['createuserform'] = userform

    return render(request, 'user/register.html', context)


def log_out(request):
    if request.user.is_active:
        logout(request)

    return redirect('/')

account/templates/user/forgot.html
{%extends 'user/main.html'%}
{%load static%}
    {% block content%}
		<div class="row pt-5 justify-content-sm-center align-items-center h-100">
			<div class="col-xxl-4 col-md-6 col-sm-9">
				<div class="card shadow-lg">
					<div class="card-body p-5">
						<h3 class="card-title mb-3">Forgot Password</h3>
						<form method="POST" class="needs-validation" novalidate="" autocomplete="off">
							<div class="mb-3">
								<label class="mb-2 label-black" for="email">E-Mail Address</label>
								<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
								<div class="invalid-feedback">
									Email is invalid
								</div>
							</div>

							<div class="d-flex align-items-center">
								<button type="submit" class="btn blue-btn ms-auto">
									Send Link	
								</button>
							</div>
						</form>
					</div>
					<div class="card-footer py-3 border-0">
						<div class="text-center">
							Remember your password? <a href="{% url 'user:userlogin' %}">Login</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	{%endblock content %}    

account/templates/user/login.html
{%extends 'main.html'%}
{%load static%}
    {% block content%}
		<div class="row justify-content-sm-center align-items-center h-100">
			<div class="col-xxl-4 col-md-5 col-sm-9">
					
					<div class="card shadow-lg">
						<div class="card-body p-5">
							<h3 class="card-title mb-3">Login</h3>
							<form method="POST" class="needs-validation" novalidate="" autocomplete="off">
								{%csrf_token%}
								<div class="mb-3">
									<label class="mb-2 label-black" for="email">E-Mail Address</label>
									<input id="email" type="email" class="form-control" name="email" value="" required autofocus>
									<div class="invalid-feedback">
										Email is invalid
									</div>
								</div>

								<div class="mb-3">
									<div class="mb-2 w-100">
										<label class="label-black"for="password">Password</label>
										<a href="{% url 'user:password_reset' %}" class="float-end">
											Forgot Password?
										</a>
									</div>
									<input id="password" type="password" class="form-control" name="password" required>
								    <div class="invalid-feedback">
								    	Password is required
							    	</div>
								</div>
								<div class="col-12 d-flex justify-content-sm-between">
									{%for field in loginform %}
										{% for error in field.errors %}
											<p style="color: red !important">{{field.label}} {{error}}</p>
										{%endfor%}
									{%endfor%}
									{%if loginform.non_field_errors%}
										<p style="color:red !important">{{loginform.non_field_errors}}</p>
									{%endif%}
							  	</div>
								<div class="d-flex align-items-center">
									<div class="form-check">
										<input type="checkbox" name="remember" id="remember" class="form-check-input">
										<label for="remember" class="form-check-label label-black">Remember Me</label>
									</div>
									<button type="submit" class="btn blue-btn ms-auto">
										Login
									</button>
								</div>
							</form>
						</div>
						<div class="card-footer py-3 border-0">
							<div class="text-center">
								Don't have an account? <a href="{% url 'user:register' %}">Create One</a>
							</div>
						</div>
					</div>
			</div>
		</div>
	{%endblock content %}    

account/templates/user/register.html
{%extends 'main.html'%}
{%load static%}
  {% block content%}
			<div class="row pt-4 justify-content-sm-center align-items-center h-100">
				<div class="col-xxl-4 col-md-6 col-sm-9">
					
					<div class="card shadow-lg">
						<div class="card-body p-5">
							<h3 class="card-title mb-3">Register</h3>
							<form class="row g-3 signin" method="post">
								{% csrf_token %}
								<div class="col-md-6">
									<label for="first-name" class="form-label label-black">First Name</label>
									<input type="text" class="form-control" name="first_name" autocomplete="off">
								</div>
								<div class="col-md-6">
									<label for="last-name" class="form-label label-black">Last Name</label>
									<input type="text" class="form-control" name="last_name" autocomplete="off">
								</div>
								<div class="col-12">
									<label for="email-address" class="form-label label-black">Email Address</label>
									<input type="email" class="form-control" name="email">
								</div>
								<div class="col-12">
								  <label for="password1" class="form-label label-black">Password</label>
								  <input type="password" class="form-control" name="password1" autocomplete="off">
								</div>
								<div class="col-12">
								  <label for="password2" class="form-label label-black">Verify Password</label>
								  <input type="password" class="form-control" name="password2" autocomplete="off">
								</div>

								<div class="col-12">
									<p class="mb-3 label-black">
										By registering you agree with our terms and condition.
									</p>
								</div>
								<div class="col-12 d-flex justify-content-sm-between">
									{%for field in createuserform %}
										{% for error in field.errors %}
											<p style="color: red !important">{{field.label}} {{error}}</p>
										{%endfor%}
									{%endfor%}
									{%if createuserform.non_field_errors%}
										<p style="color:red !important">{{createuserform.non_field_errors}}</p>
									{%endif%}
							  	</div>

								<div class="align-items-center d-flex">
									<button type="submit" name="save_others" class="btn blue-btn ms-auto" id="submit-btn">
										Register	
									</button>
								</div>
							</form>
						</div>
						<div class="card-footer py-3 border-0">
							<div class="text-center">
								Already have an account? <a href="{% url 'user:login' %}">Login</a>
							</div>
						</div>
					</div>
				</div>
			</div>
	{%endblock content %}    