account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'user'

urlpatterns = [
    path('login/', views.user_login, name="login"),
    path('register/', views.register, name="register"),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='password_managment/forgot.html',
            email_template_name='password_managment/password_reset_email.html',
            success_url=reverse_lazy('user:password_reset_done')),
        name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_managment/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password_managment/reset.html',
             success_url=reverse_lazy('user:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password_managment/password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.log_out, name="log_out")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
import store.urls
import account.urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(store.urls)),
    path('user/', include(account.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name="index"),
    path('store/', views.store, name="store"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('product/<int:pk>/', views.product, name="product"),
    path('update_item/', views.update_item, name="update_item"),
    path('payment/', views.payment, name="payment"),
    path('payment_output/', views.payment_output, name="payment_output")
]

store/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class CustomerModel(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                null=True,
                                blank=True,
                                on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=200)

    def __str__(self):
        return self.email


class ProductModel(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.CharField(max_length=400, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    is_sale = models.BooleanField(default=False, null=True, blank=True)
    sale_price = models.DecimalField(max_digits=8,
                                     decimal_places=2,
                                     null=True,
                                     blank=True)

    def __str__(self):
        return self.name

    #A property decorator make an attribute out of a function
    #That's why they're mentioned in the docs like 'managed attributes'
    #This function tries to get the image for the template
    #it's used to prevent no-images products
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url


class OrderModel(models.Model):
    customer = models.ForeignKey(CustomerModel,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_order_items(self):
        return self.orderitemmodel_set.all()

    @property
    def get_order_total(self):
        #This a reverse lookup based on the 1 to Many relationship
        #between OrderModel and OrderItemModel
        orderitems = self.orderitemmodel_set.all()
        total = sum([orderitem.get_total for orderitem in orderitems])
        return total

    @property
    def get_order_quantity(self):
        orderitems = self.orderitemmodel_set.all()
        quantity = sum([orderitem.quantity for orderitem in orderitems])
        return quantity


class OrderItemModel(models.Model):
    product = models.ForeignKey(ProductModel,
                                on_delete=models.SET_NULL,
                                null=True,
                                blank=True)
    order = models.ForeignKey(OrderModel,
                              on_delete=models.SET_NULL,
                              blank=True,
                              null=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        if not self.product.is_sale:
            return self.product.price * self.quantity
        else:
            return self.product.sale_price * self.quantity


class ShippingModel(models.Model):
    customer = models.ForeignKey(CustomerModel,
                                 on_delete=models.SET_NULL,
                                 null=True)
    order = models.ForeignKey(OrderModel, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

store/forms.py
from django import forms
from account.models import Account

class UserShippingDataForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    is_logged = forms.CharField(max_length=10)
    email = forms.EmailField(max_length=200)
    address = forms.CharField(max_length=200)
    city = forms.CharField(max_length=200)
    state = forms.CharField(max_length=200)
    zipcode = forms.CharField(max_length=200)    
    total = forms.FloatField(required=False)
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        if self.cleaned_data['is_logged']:
            return email
        try:
            account = Account.objects.get(email=email)   
        except:
            return email
        raise forms.ValidationError('is already in use')
    
    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name.lower()
        else:
            raise forms.ValidationError('First Name must be alphabetical')
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name.lower()
        else:
            raise forms.ValidationError('Last Name must be alphabetical') 
        
    def clean_is_logged(self):
        is_logged = self.cleaned_data['is_logged']
        if is_logged == 'True':
            return True
        else:
            return False

store/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import datetime
from .models import *
from .forms import *
from .utils import get_cart, get_order, create_preferences
# Create your views here.


def index(request):
    cart = get_cart(request)
    products_sale = ProductModel.objects.all().filter(is_sale=True)[:8]
    products = ProductModel.objects.all().filter(is_sale=False)[:8]
    context = {
        'items': cart['items'],
        'order': cart['order'],
        'cart_items': cart['cart_items'],
        'products_sale': products_sale,
        'products': products
    }
    return render(request, 'store/index.html', context)


def store(request):
    cart = get_cart(request)
    products = ProductModel.objects.all()
    context = {
        'items': cart['items'],
        'order': cart['order'],
        'cart_items': cart['cart_items'],
        'products': products
    }
    return render(request, 'store/store.html', context)


def product(request, pk):
    cart = get_cart(request)
    product = ProductModel.objects.get(pk=pk)
    context = {
        'items': cart['items'],
        'order': cart['order'],
        'cart_items': cart['cart_items'],
        'product': product
    }
    return render(request, 'store/product.html', context)


def cart(request):
    cart = get_cart(request)
    context = {
        'items': cart['items'],
        'order': cart['order'],
        'cart_items': cart['cart_items']
    }
    response = render(request, 'store/cart.html', context)
    return response


def checkout(request):
    cart = get_cart(request)
    context = {
        'items': cart['items'],
        'order': cart['order'],
        'cart_items': cart['cart_items']
    }
    if request.POST:
        usershippingform = UserShippingDataForm(request.POST)
        if usershippingform.is_valid():
            customer, order = get_order(request, usershippingform)
            total = usershippingform.cleaned_data['total']
            order.transaction_id = datetime.datetime.now().timestamp()
            if total == float(order.get_order_total):
                #redirect to payment view
                order.save()
                ShippingModel.objects.create(
                    customer=customer,
                    order=order,
                    city=usershippingform.cleaned_data['city'],
                    state=usershippingform.cleaned_data['state'],
                    zipcode=usershippingform.cleaned_data['zipcode'],
                    address=usershippingform.cleaned_data['address'])
                response = redirect('/payment')
                response.set_cookie('order_id', order.id)
                return response
        else:
            context['usershippingform'] = usershippingform
    return render(request, 'store/checkout.html', context)


def payment(request):
    context = {'error': False}
    try:
        order_id = request.COOKIES['order_id']
        order = OrderModel.objects.get(id=order_id)
        if order.complete == False:
            preference_data = create_preferences(order)
            context['preference'] = preference_data['preference']
            context['PUBLIC_KEY'] = preference_data['PUBLIC_KEY']
        else:
            raise Exception
    except:
        context['error'] = True
    return render(request, 'store/payment.html', context)


def payment_output(request):
    response = redirect('/')
    try:
        data = request.GET
        if data['collection_status'] == 'approved':
            order_id = data['external_reference']
            order = OrderModel.objects.get(id=order_id)
            order.complete = True
            order.save()
            response.delete_cookie('cart')
    except:
        pass
    return response

#This view is only used by authenticated users
#the updates of a guest's cart are managed by cookies
def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    customer = request.user.customermodel
    product = ProductModel.objects.get(id=productId)

    order, created = OrderModel.objects.get_or_create(customer=customer,
                                                      complete=False)
    order_item, created = OrderItemModel.objects.get_or_create(product=product,
                                                               order=order)

    if action == "add":
        order_item.quantity = order_item.quantity + 1
    elif action == "remove":
        order_item.quantity = order_item.quantity - 1

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse('item was added', safe=False)

store/templates/store/cart.html
{%extends 'store/main.html'%}
{%load static%}
    {% block content%}
        <div class="row pt-5">
            <div class="col-sm-12">
                <div class="card shadow-lg">
                    <div class="card-body p-5">
                        <div class="d-flex flex-md-row flex-column justify-content-between pt-3 ps-5">
                            <div class="p-5"><h5>Items: <strong>{{order.get_order_quantity}}</strong></h5></div>
                            <div class="p-5"><h5>Total: <strong>${{order.get_order_total}}</strong></h5></div>
                            <div class="p-5"><a href="{% url 'store:checkout' %}" class="ps-3"><button type="button" class="btn blue-btn">Checkout</button></a></div>
                        </div>
                        <hr>

                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-5 h-100">
            <div class="col-sm-12">
                <div class="card shadow-lg">
                    <div class="card-body">
                        <hr>
                        {%for item in items%}
                        <div class="d-flex flex-md-row flex-column justify-content-center align-items-center pt-3 ps-5">
                            <div class="p-3 flex-fill"><img src="{{item.product.imageURL}}" class="sm-image"></div>
                            <div class="p-3 flex-fill"><p>{{item.product.name}}</p></div>
                            {%if item.product.is_sale%}
                                <div class="p-3 flex-fill"><p>$ {{item.product.sale_price}}</p></div>
                            {%else%}
                                <div class="p-3 flex-fill"><p>$ {{item.product.price}}</p></div>
                            {%endif%}
                            <div class="p-3 flex-fill">
                                    <span>{{item.quantity}}</span>
                                    <img src="{% static 'images/up.png' %}" alt="" class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action='add'>
                                    <img src="{% static 'images/down.png' %}" alt="" class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action='remove'>         
                            </div>
                            <div class="p-3 flex-fill"><p>$ {{item.get_total}}</p></div>
                        </div>
                        <hr>
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>
    {%endblock content %}

store/templates/store/index.html
{%extends 'store/main.html'%}
{%load static%}
    {% block content%}
        <div class="row justify-content-evenly m-5 mt-0" style="background-color: #ffffff;">
            <div class="col-lg-6 col-md-8 col-xs-12 align-self-center">
                <div class="hero-text">
                    <span class="hero-title">Samsung Galaxy 10</span>
                    <p class="hero-desc">Push the boundaries of technology to give our customers an enhanced mobile experience</p>
                </div>
                
            </div>
            <div class="col-lg-4 col-md-8 col-xs-12 align-self-center">
                <img src="{% static 'images/samsung.png' %}" class="img-fluid p-2" alt="">
            </div>
        </div>
        <!-- For Sale -->
        <div class="row justify-content-center pt-5">
            <div class="col-xs-12 col-md-12 col-lg-8 align-self-start">
                <span style="font-weight: 500; font-size: 36px;">For sale</span>
                <div class="card-group multiple-items pt-3">
                    {%for product in products_sale %}
                            <div class="card text-center h-100 sale">
                                <a href="{% url 'store:product' pk=product.pk %}">
                                    <img src="{{product.imageURL}}" class="card-img-top index-store-image">
                                    <div class="card-body" style="color:#393D46">
                                        <h5 class="card-title text-truncate" style="font-size: 14px;">{{product.name}}</h5>
                                        <div class="card-text">
                                            <span class="card-text" style="font-size: 10px; text-decoration: line-through; color:#a7a7a8">$ {{product.price|floatformat:2}}</span>
                                        <span style="font-size: 12px;color: green !important;">$ {{product.sale_price|floatformat:2}}</span>
                                        </div> 
                                    </div> 
                                </a>     
                            </div>
                    {%endfor%}
                </div>
            </div>
        </div>

        <!-- Store -->
        <div class="row justify-content-center pt-5">
            <div class="col-xs-12 col-md-12 col-lg-8 align-self-start">
                <span style="font-weight: 500; font-size: 36px;">Products</span>
                <a href="{% url 'store:store' %}" style="font-weight: 300; font-size: 18px; padding-left: 1em;">View All</a>
                <div class="card-group multiple-items pt-3">
                    {%for product in products %}
                            <div class="card text-center h-100">
                                <a href="{% url 'store:product' pk=product.pk %}">
                                    <img src="{{product.imageURL}}" class="card-img-top index-store-image">
                                    <div class="card-body" style="color:#393D46">
                                        <h5 class="card-title text-truncate" style="font-size: 14px;">{{product.name}}</h5>
                                        <p class="card-text" style="font-size: 12px;">$ {{product.price|floatformat:2}}</p>
                                    </div> 
                                </a>     
                            </div>
                    {%endfor%}
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-2 about">
            <div class="col-xs-12 col-md-4 col-lg-4">
                <img src="{% static 'images/latest.svg' %}" class="sm-image mt-2 mb-2" alt="">
                <p>Enjoy the best prices for high quality technology.</p>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 border-start border-end">
                <img src="{% static 'images/security.svg' %}" class="sm-image mt-2 mb-2" alt="">
                <p>We provide free shipping worldwide. You can order from anywhere, anytime.</p>
                
            </div>
            <div class="col-xs-12 col-md-4 col-lg-4">
                <img src="{% static 'images/logistic.svg' %}" class="sm-image mt-2 mb-2" alt="">
                <p>We are a team of dedicated, hard-working individuals with a passion for tech.</p>
            </div>
        </div>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {%endblock content%}

store/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
    <script type="text/javascript">
      var user = "{{request.user}}"
      const csrf_token = "{{csrf_token}}"
      function getCookie(name){
        var cookieArr = document.cookie.split(';')

        for(var i = 0; i < cookieArr.length; i++){
          var cookiePair = cookieArr[i].split('=')

          if (name == cookiePair[0].trim()){
            return decodeURIComponent(cookiePair[1]);
          }
        }
        return null;
      }
      var cart = JSON.parse(getCookie('cart'))

      if (cart == undefined){
        cart = {}
        document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/'
        console.log('Cookie created')
      }
    </script>
    <title>Volkshop</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm store-navbar">
      <a class="navbar-brand logo" href="{% url 'store:index' %}">Volkshop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-auto nav-links">
          <a href="{% url 'store:cart' %}">
              <img src="{% static 'images/cart.png' %}" class="xs-image pe-1" alt="cart">
          </a>
          <p id="cart-total">{{cart_items}}</p>
          {%if request.user.is_authenticated %}
            <a href="{% url 'user:log_out' %}" class="ps-3"><button type="button" class="btn blue-btn">Log Off</button></a>
          {% else %}
            <a href="{% url 'user:login' %}" class="ps-3"><button type="button" class="btn blue-btn">Login</button></a>
          {%endif%}
        </div>
      </div>
    </nav>
    <div class="container h-100">
        {%block content%}
        {%endblock content%}
    </div>
    <!-- <script src="{% static 'js/form.js' %}"></script> -->
    <script type="text/javascript" src="{%static 'js/cart.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

store/templates/store/payment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Volkshop</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm user-navbar blue">
        <a class="navbar-brand logo" href="{% url 'store:index' %}">Volkshop</a>
      </nav>
    
    <div class="container-fluid h-100 split-color">
        {%if error%}
            <div class="row pt-5 justify-content-sm-center align-items-center h-100">
                <div class="col-xxl-4 col-md-6 col-sm-9">
                    <div class="card shadow-lg">
                        <div class="card-body p-5">
                            <p class="m-auto p-2">
                                There was an error processing your order, please try again later.
                            </p>
                            <p class="m-auto p-2"><a href="{% url 'store:index' %}">Return to home page</a></p>
                        </div>
                    </div>
                </div>
            </div>
        {%else%}  
            <script src="https://sdk.mercadopago.com/js/v2"></script>

            <script>
                // Agrega credenciales de SDK
                const mp = new MercadoPago("{{PUBLIC_KEY}}", {
                        locale: 'es-AR'
                });
                
                // Inicializa el checkout
                const checkout = mp.checkout({
                    preference: {
                        id: "{{preference.id}}"
                    },
                    autoOpen: true,
                });
            </script>
        {%endif%}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

store/templates/store/product.html
{%extends 'store/main.html'%}
{%load static%}
{% block content%}
        <div class="container w-75 pt-5">
            <!-- Product -->
            <div class="row justify-content-around align-items-center pb-5 pt-2 pe-5 ps-5" style="background-color: #ffffff;">
                <div class="col-lg-4 col-md-8 col-sm-12 col-xs-12 pt-4">
                    <img src="{{product.imageURL}}" class="product-image me-3" alt="">
                </div>
                <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12 pt-4">
                    <div class="product-text">
                        <span class="product-title w-50">{{product.name}}</span>
                        <p class="product-desc">{{product.description}}</p>
                        {%if product.is_sale%}
                            <div class="card-text fs-3">
                                <span style="text-decoration: line-through; color:#a7a7a8">$ {{product.price|floatformat:2}}</span>
                                <span style="color: green !important;">$ {{product.sale_price|floatformat:2}}</span>
                            </div> 
                        {%else%}
                            <p class="fs-3">${{product.price}}</p>
                        {%endif%}
                        <button type="button" class="btn blue-btn update-cart" data-product="{{product.id}}" data-action='add'>
                            Add to Cart</button>
                    </div>
                    
                </div>
            </div>
        </div>
    {%endblock content %}    

store/templates/store/store.html
{%extends 'store/main.html'%}
{%load static%}
  {% block content%}
    <div class="container container-store">
        <div class="row store row-cols-1 row-cols-md-4 g-4 pb-5">
            <div class="col-sm-12">
                <span style="font-weight: 500; font-size: 36px;">Store</span>
            </div>

            {% for product in products %}
                {%if product.is_sale %}
                    <div class="col products">
                        <div class="card text-center h-100 sale">
                            <a href="{% url 'store:product' pk=product.pk %}">
                                <img src="{{product.imageURL}}" class="card-img-top index-store-image">
                                <div class="card-body" style="color:#393D46">
                                    <h5 class="card-title text-truncate" style="font-size: 14px;">{{product.name}}</h5>
                                    <div class="card-text">
                                        <span style="font-size: 10px; text-decoration: line-through; color:#a7a7a8">$ {{product.price|floatformat:2}}</span>
                                        <span style="font-size: 12px;color: green !important;">$ {{product.sale_price|floatformat:2}}</span>
                                    </div> 
                                </div> 
                            </a>     
                        </div>
                    </div>
                {%else%}
                    <div class="col products">
                        <div class="card text-center h-100">
                            <a href="{%url 'store:product' pk=product.pk%}">
                                <img src="{{product.imageURL}}" class="card-img-top index-store-image">
                                <div class="card-body" style="color:#393D46">
                                    <h5 class="card-title" style="font-size: 14px;">{{product.name}}</h5>
                                    <p class="card-text" style="font-size: 12px;">$ {{product.price}}</p>
                                </div> 
                            </a>  
                        </div>
                    </div>
                {%endif%}
            {%endfor%}
        </div>
    </div>
    {%endblock content %}    